### PR TITLE
Fixed failure to apply a default language after a request with specified language

### PR DESCRIPTION
**Pull request by bauerbrun0**
## Description:

This pull request addresses the [issue](https://github.com/eelkevdbos/elysia-i18next/issues/4) where the application, after a request with a specified language, fails to revert to a default language when the subsequent request does not specify a language. The current behavior retains the previous language instead of falling back to a default language, eg. the one set in `initOptions.lng`.

## Changes Made:

1. **Code Modification:**
   - Updated the logic in `onBeforeHandle`; If a language is not detected and the new `useLngAsDefault` option is true, it falls back to the default language specified in `initOptions.lng`.
   
        ```ts
        // src/index.ts
        .onBeforeHandle(async ctx => {
            const detectedLanguage = await options.detectLanguage(ctx)
            if (detectedLanguage) {
                await _instance.changeLanguage(detectedLanguage)
                return
            }

            const { options: { lng }, language: currentLanguage } = _instance

            if (options.useLngAsDefault && lng && currentLanguage !== lng) {
                await _instance.changeLanguage(lng)
	        }
        })
        ```

2. **New Option:**
   - Introduced a new option `useLngAsDefault` (defaults to `true`) to control whether the application should use the default language when a language is not specified/detected in a request.

        ```ts
        const app = new Elysia()
            .use(i18next({ instance, useLngAsDefault: true }))
            .get('/', ({ t }) => t('greeting'))
        ```

3. **Test Cases:**
   - Added a new test case to validate that the application falls back to the default language after a request with a specified language.
   - Added a test case to verify that opting out from using the default language (`useLngAsDefault: false`) works as intended.

4. **Documentation:**
   - Updated the README to include information about the new option `useLngAsDefault`.

**Thank you for reviewing this pull request!**

### CODE REVIEW

**Comment by eelkevdbos** [comment]
Hey! Sorry for the wait, I'll have a look at your contribution today. I have been messing around a bit with the language (detection) and the behaviour is not yet where I want it to be, but maybe this solves those issues.

**Comment by eelkevdbos** [comment]
The test case you have submitted is valid, thank you for that contribution!

I'd like to go for a slightly different solution to the one that you have implemented. To ensure complete isolation from other requests, I'd like to clone a fresh instance (with configured defaults) of the library on each request.

The rationale behind it is that I could see settings persist other than the current language and that would create a whole range of settings to make sure that the defaults are restored / used on subsequent requests.

Added benefit of cloning is that I am also eyeing the use of i18n in an async context, for example, rendering translations (for the currently set language) in jsx components (https://github.com/kitajs/html/issues/31).

**Comment by morigs** [comment]
@eelkevdbos Do you still have plans on implementing this? Also, looking forward for #9 

Please give me know if there a way to help

**Comment by eelkevdbos** [comment]
> @eelkevdbos Do you still have plans on implementing this? Also, looking forward for #9
> 
> Please give me know if there a way to help

Sorry for the wait, I have a tentative implementation ready.

**Pull request closed without merging**
